<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <meta charset="UTF-8">
    <title>Login admin</title>

</head>
<body>
<div>
    <form action="/login" method="post">
       <div> <input type="text" name="username" placeholder="User's name"/></div>
       <div> <input type="password" name="password" placeholder="User's password"/></div>
        <button type="submit"> Login</button>
    </form>
</div>
</body>
</html>